version: '3.8'

services:

  # ======================
  # MySQL
  # ======================
  mysql:
    image: mysql:8.0
    container_name: crm-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - crm-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ======================
  # Zookeeper
  # ======================
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - crm-network

  # ======================
  # Kafka
  # ======================
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"       # внутренний Docker порт
      - "29092:29092"     # порт для localhost
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - crm-network
    healthcheck:
      test: [ "CMD", "bash", "-c", "echo > /dev/tcp/localhost/9092" ]
      interval: 10s
      retries: 10

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: crm-phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    depends_on:
      - mysql
    networks:
      - crm-network

  # ======================
  # Eureka Server
  # ======================
  eureka-server:
    build:
      context: .
      dockerfile: infrastructure/eureka-server/Dockerfile
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - crm-network

  # ======================
  # Config Server
  # ======================
  config-server:
    build:
      context: .
      dockerfile: infrastructure/config-server/Dockerfile
    container_name: config-server
    ports:
      - "8888:8888"
    depends_on:
      - eureka-server
    networks:
      - crm-network

  # ======================
  # API Gateway
  # ======================
  api-gateway:
    build:
      context: .
      dockerfile: infrastructure/api-gateway/Dockerfile
    container_name: api-gateway
    ports:
      - "8088:8088"
    depends_on:
      - eureka-server
      - config-server
    networks:
      - crm-network

  # ======================
  # User Service
  # ======================
  user-service:
    build:
      context: .
      dockerfile: services/user-service/Dockerfile
    container_name: user-service
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
      config-server:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/users_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - crm-network

  # ======================
  # Auth Service
  # ======================
  auth-service:
    build:
      context: .
      dockerfile: services/auth-service/Dockerfile
    container_name: auth-service
    depends_on:
      - user-service
      - eureka-server
      - config-server
    networks:
      - crm-network

  # ======================
  # Customer Service
  # ======================
  customer-service:
    build:
      context: .
      dockerfile: services/customer-service/Dockerfile
    container_name: customer-service
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
      config-server:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/customers_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - crm-network

  # ======================
  # Logging Service
  # ======================
  logging-service:
    build:
      context: .
      dockerfile: logging-service/Dockerfile
    container_name: logging-service
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
      config-server:
        condition: service_started
      kafka:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/logging_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - crm-network

  # ======================
  # Product Service
  # ======================
  product-service:
    build:
      context: .
      dockerfile: services/product-service/Dockerfile
    container_name: product-service
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
      config-server:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/products_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - crm-network

  # ======================
  # Order Service
  # ======================
  order-service:
    build:
      context: .
      dockerfile: services/order-service/Dockerfile
    container_name: order-service
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
      config-server:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/orders_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - crm-network

  # ======================
  # Order Service
  # ======================
  billing-service:
    build:
      context: .
      dockerfile: services/billing-service/Dockerfile
    container_name: billing-service
    depends_on:
      mysql:
        condition: service_healthy
      eureka-server:
        condition: service_started
      config-server:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/billing_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - crm-network

# ======================
# Network
# ======================
networks:
  crm-network:
    driver: bridge