server:
  port: 8088

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:

        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/customers/**
        - id: logging-service
          uri: lb://logging-service
          predicates:
            - Path=/logging/**
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/products/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/orders/**
        - id: billing-service
          uri: lb://billing-service
          predicates:
            - Path=/billing/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notification/**

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health