server:
  port: 8087

spring:
  application:
    name: billing-service

  datasource:
    url: jdbc:mysql://mysql:3306/billing_db
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: billing-group
      auto-offset-reset: earliest

      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

      properties:
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.crm.common.dto.OrderCreatedEvent

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/